name: PatheticTest
version: '${project.version}'
main: org.patheloper.example.PatheticPlugin
api-version: 1.21
authors:
  - olijeffers0n
  - GodCipher

commands:
  pathetic:
    description: What a pathetic command
    aliases:
      - path
      - pathfinder
