name: PatheticTest
version: '${project.version}'
main: xyz.ollieee.example.PatheticPlugin
api-version: 1.19
authors:
  - olijeffers0n
  - GodCipher

commands:
  pathetic:
    description: What a pathetic command
