name: Deploy Javadoc

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Generate Javadoc
        run: |
          mvn javadoc:aggregate -pl :pathetic-api
        shell: bash
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          folder: javadoc
